### ISSUE TITLE
Environments Check for Exclusive Locks

### ISSUE THREAD

**Issue by bartvdbraak** [microsoft/terraform-provider-azuredevops#830]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* (new) `azuredevops_check_exclusive_lock`

### Potential Terraform Configuration

```hcl
resource "azuredevops_project" "example" {
  name = "Example Project"
}

resource "azuredevops_environment" "example" {
  project_id = azuredevops_project.example.id
  name       = "Example Environment"
}

data "azuredevops_users" "example" {
  principal_name = "someone@somewhere.com"
}

resource "azuredevops_check_exclusive_lock" "example" {
  project_id           = azuredevops_project.example.id
  target_resource_id   = azuredevops_environment.example.id
  target_resource_type = "environment"

  timeout = 43200
}
```

Current workaround I am using using `local-exec` provider on `create`. It has a retry in there to try and catch any rate-limiting issues.

```
variable "pat" {
  type        = string
  description = "Personal Access Token needed to create the Service Connections in Azure Devops"
}

resource "azuredevops_project" "example" {
  name = "Example Project"
}

locals {
  organization = "testorg"
  environments = ["Example Environment"]
  environments_with_xlock = ["Example Environment"]
}

resource "azuredevops_environment" "environment" {
  for_each = { for env in local.environments : env => env }

  project_id = data.azuredevops_project.example.id
  name       = each.key

  // Set Exclusive locks
  
  provisioner "local-exec" {
    when    = create
    command = <<-EOT
      if [[ "$(echo ${contains(local.environments_with_xlock, each.key) ? "true" : "false"} )" == "true" ]]; then
        retry_count=0
        while [ $retry_count -lt 3 ]; do
          sleep $((1 + $RANDOM % 4))
          response=$(curl \
            --silent \
            -o /dev/null -w "%%{http_code}" \
            --request POST \
            --url 'https://dev.azure.com/${local.organization}/${data.azuredevops_project.example.id}/_apis/pipelines/checks/configurations?api-version=7.0-preview.1' \
            --header "Authorization: Basic $PAT_BASE64_ENCODED" \
            --header 'Content-Type: application/json' \
            --data '{
              "type": {
                "id": "2EF31AD6-BAA0-403A-8B45-2CBC9B4E5563",
                "name": "ExclusiveLock"
              },
              "resource": {
                "type": "environment",
                "id": "${self.id}",
                "name": "${each.key}"
              }
            }')
          status_code=$(echo "$response" | tail -n1)
          if [[ "$status_code" -ge 200 && "$status_code" -lt 300 ]]; then
            break
          fi
          retry_count=$((retry_count + 1))
        done
      else
        echo "No exclusive lock needed"
      fi
    EOT
    environment = {
      PAT_BASE64_ENCODED = base64encode(format(":%s", var.pat))
    }
    interpreter = ["/bin/bash", "-c"]
  }
}
```

### References

```[tasklist]
### Tasks
- [x] `azuredevops/internal/service/approvalsandchecks/resource_check_exclusive_lock_test.go`
- [x] `azuredevops/internal/service/approvalsandchecks/resource_check_exclusive_lock.go`
- [x] changes to `azuredevops/provider.go`, `azuredevops/provider_test.go` and `azuredevops/internal/service/approvalsandchecks/common_check.go`
- [x] `azuredevops/internal/acceptancetests/resource_check_exclusive_lock_test.go`
- [x] changes to `website/azuredevops.erb` and create `website/docs/r/check_exclusive_lock.html.markdown`
```

**Comment by bartvdbraak** [comment]
Currently working on an implementation for it. 

See the following branch in my fork: https://github.com/bartvdbraak/terraform-provider-azuredevops/tree/feat/830-check-exclusive-lock
